sudo: required
language: node_js
node_js:
- node
deploy:
  provider: npm
  email: sobreiro.pedro@gmail.com
  api_key:
    secure: bgImDbbShMiWWlYkmg5Cxlj7HahxjYQBrwzopUwbXok6uo6ihO7EoBy8RPc8hiXBXQdoY79Iy2kwO6Didvam5O71851gEunw2unwZWnTOldYbNhh79UJwFlf4dhFcwk4XQKNfs/NH0iZSCikkAnAASzGG1kn9yU+j1fZVeaLcHpN7eMHZlToM219wmANYyNWuajO8lkb3Omy6Ou82owbqqRL2+K36MUZEfRaYXnJscSEWWPY/qMd1kp4JbaOsGYenzKvMkQ2wUcQemv5fsWfXZyEPkfNOAjzlItaGhCiPuGG9e/MWMXjF+ztNA3kFV9uel0PE+LvpNuhF1bMt0P/lK3PbUhOQI2RrslRQ3k5G+z1WLAi0tVcQk3WcsFnHX3nMfNJ6uF+G2E0Z49qRzXSTMyEeGHYlJPm3lnpFWk8ddKn3oGFnJNLqs/kOFnV4OOcXtpfWmfBlFq3gZfHh0tjiYgcEmr+roiS4a7KC9BSJLqQZ/l93O1NqR2vEO2oFwvSJT/mG9oVsDwiwNYxqlc7l+e7e9HaPlDwm25La/mYOR1eZFXTZJukHfLUyQyeeduiKNOB5RFoGpfoV8c2rJ0f6EXJsTpTb6XQC4UKwdXVCP36syMqkfHrn6ZLPqAdS1qt6tJlJA9qgBSq/CmjWVwIJnqqkrn2MqooZi7C7w3rdIY=
  on:
    tags: true
    repo: criticalmanufacturing/generator-html
